
spring:
  application:
    name= user-interface:
  datasource:
    url: jdbc:mysql://localhost:3306/finance_user
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
#  redis:
#    host: localhost
#    port: 6379
#  session:
#    store-type: redis

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8086